// export const LANGUAGES = [
//     {value: 'Assamese'},
//     {value: 'Bengali'},
//     {value: 'Bodo'},
//     {value: 'Bhil'},
//     {value: 'Bhojpuri'},
//     {value: 'Dogri'},
//     { value: 'Gondi'},
//     { value: 'Gujarati'},
//     { value: 'Hindi'},
//     { value: 'Kannada'},
//     { value: 'Kashmiri'},
//     { value: 'Khandeshi'},
//     { value: 'Konkani'},
//     { value: 'Kurukh'},
//     { value: 'Maithili'},
//     { value: 'Malayalam'},
//     { value: 'Meitei'},
//     { value: 'Marathi'},
//     { value: 'Nepali'},
//     { value: 'Odia'},
//     { value: 'Punjabi'},
//     { value: 'Sanskrit'},
//     { value: 'Santali'},
//     { value: 'Sindhi'},
//     { value: 'Tamil'},
//     { value: 'Telugu'},
//     { value: 'Tulu'},
//     { value: 'Ho'},
//     { value: 'Urdu'},
//     { value: 'Mundari'},
//     { value: 'Khasi'},
//     { value: 'Tripuri'},
//     { value: 'Garo'},
//     { value: 'Nagamese'},
//     { value: 'Mizo'},
//     { value: 'Ladakhi'},
//     { value: 'Mandarin'},
//     { value: 'Spanish'},
//     { value: 'English'},
//     { value: 'Portuguese'},
//     { value: 'Russian'},
//     { value: 'Japanese'},
//     { value: 'Cantonese'},
//     { value: 'Vietnamese'},
//     { value: 'Turkish'},
//     { value: 'Shanghainese'},
//     { value: 'Korean'},
//     { value: 'French'},
//     { value: 'German'},
//     { value: 'Arabic'},
//     { value: 'Javanese'},
//     { value: 'Persian'},
//     { value: 'Hausa'},
//     { value: 'Swahili'},
//     { value: 'Italian'},
//     { value: 'Thai'},
//     { value: 'Amharic'},
//     { value: 'Yoruba'},
//     { value: 'Burmese'},
//     { value: 'Polish'},
// ];

export const LANGUAGES = [
    "Arabic",
    "Assamese",
    "Bengali",
    "Bhil",
    "Bhojpuri",
    "Bodo",
    "Burmese",
    "Cantonese",
    "Dogri",
    "English",
    "French",
    "Garo",
    "German",
    "Gondi",
    "Gujarati",
    "Hindi",
    "Ho",
    "Italian",
    "Japanese",
    "Kannada",
    "Kashmiri",
    "Khandeshi",
    "Khasi",
    "Konkani",
    "Korean",
    "Kurukh",
    "Ladakhi",
    "Maithili",
    "Malayalam",
    "Mandarin",
    "Marathi",
    "Meitei",
    "Mizo",
    "Mundari",
    "Nagamese",
    "Nepali",
    "Odia",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Russian",
    "Sanskrit",
    "Santali",
    "Sindhi",
    "Spanish",
    "Tamil",
    "Telugu",
    "Thai",
    "Tripuri",
    "Tulu",
    "Turkish",
    "Urdu",
    "Vietnamese"
];